### ISSUE TITLE
打开不了

### ISSUE THREAD

**Issue by Chuhan1112** [popeyelau/dogeTV_macOS#1]
Mojave 10.14.5 Beta (18F108f)
安装后无法打开

**Comment by popeyelau** [comment]
@Chuhan1112 请提供 异常信息 或 截图。

**Comment by Chuhan1112** [comment]
<img width="1187" alt="屏幕快照 2019-04-23 下午8 39 23" src="https://user-images.githubusercontent.com/35064712/56581649-fe5fb480-6607-11e9-9331-6b72316d5bb9.png">
<img width="1187" alt="屏幕快照 2019-04-23 下午8 39 17" src="https://user-images.githubusercontent.com/35064712/56581651-00c20e80-6608-11e9-95d7-15929bd0d688.png">

**Comment by popeyelau** [comment]
@Chuhan1112 
看上去是签名的问题。
你下载的是 [V1.0.1](https://github.com/popeyelau/dogeTV_macOS/releases/download/v1.0.1/dogeTV.app.zip) 这个版本吗？

**Comment by Chuhan1112** [comment]
> @Chuhan1112 
> 看上去是签名的问题。
> 你下载的是 [V1.0.1](https://github.com/popeyelau/dogeTV_macOS/releases/download/v1.0.1/dogeTV.app.zip) 这个版本吗？

我两个版本都试了一下，也都一样

**Comment by popeyelau** [comment]
@Chuhan1112 待我查查先。 没有 beta 版的机器，暂时无法复现。

**Comment by CrisChr** [comment]
我也遇到了同样的问题

**Comment by popeyelau** [comment]
@Chuhan1112 @CrisChr  
Try [1.0.4](https://github.com/popeyelau/dogeTV_macOS/releases/tag/1.0.4)

**Comment by Chuhan1112** [comment]
解决。感谢作者
