### ISSUE TITLE
在线升级内存爆满,直播看不了!!!

### ISSUE THREAD

**Issue by Jonnyan404** [popeyelau/dogeTV_macOS#3]
1. 基本上每次在线升级relauncher进程会在1分钟内,把内存吃满.....mbp  OS X 10.14.5
2. 电视直播看不了
3. 部分视频不提供在线直播了~~

**Comment by popeyelau** [comment]
@Jonnyan404 

> 1. 基本上每次在线升级relauncher进程会在1分钟内,把内存吃满.....mbp OS X 10.14.5

暂时没办法重现

> 2. 电视直播看不了

将以下域名添加到代理列表
- `iptv188.com`



其它问题，麻烦直接 [Telegram](https://t.me/popeyelau) 联系我
