### ISSUE TITLE
电视直播

### ISSUE THREAD

**Issue by GX-HING** [popeyelau/dogeTV_macOS#4]
**电视直播，每一个频道都无法播放，
点击频道转几圈就没反应了。**

**Comment by popeyelau** [comment]
@GX-HING 

需要将以下域名添加到代理列表中
iptv188.com

**Comment by GX-HING** [comment]
> @GX-HING
> 
> 需要将以下域名添加到代理列表中
> iptv188.com

能告诉我大概步骤吗？
软件界面没有找到添加代理的相关选项。

**Comment by popeyelau** [comment]
> > @GX-HING
> > 需要将以下域名添加到代理列表中
> > iptv188.com
> 
> 能告诉我大概步骤吗？
> 软件界面没有找到添加代理的相关选项。

如果你用 [ShadowsocksX-NG](https://github.com/shadowsocks/ShadowsocksX-NG) 的话，

`Edit User Rules For PAC` -> 增加 `iptv188.com` 保存并重启ShadowsocksX-NG即可。

其它软件同理

**Comment by GX-HING** [comment]
> > > @GX-HING
> > > 需要将以下域名添加到代理列表中
> > > iptv188.com
> > 
> > 
> > 能告诉我大概步骤吗？
> > 软件界面没有找到添加代理的相关选项。
> 
> 如果你用 [ShadowsocksX-NG](https://github.com/shadowsocks/ShadowsocksX-NG) 的话，
> 
> `Edit User Rules For PAC` -> 增加 `iptv188.com` 保存并重启ShadowsocksX-NG即可。
> 
> 其它软件同理

**已经将“iptv188.com“添加到 ShadowsocksX-NG PCA用户规则，但依然无法播放直播列表中的任何频道，**

**Comment by popeyelau** [comment]
@GX-HING 没有问题，我刚试了
![cover](https://ae01.alicdn.com/kf/Hc3dd43c5465b4819a8e179d9cb52a0d4k.png)

**Comment by GX-HING** [comment]
> @GX-HING 没有问题，我刚试了
> ![cover](https://camo.githubusercontent.com/6e64d96d350fcaa8b633b2ae0efec3a086b44685/68747470733a2f2f616530312e616c6963646e2e636f6d2f6b662f4863336464343363353436356234383139613865313739643963623532613064346b2e706e67)

**是不是我的方法错了呢？这是NG的规则列表**
![](https://github.com/GX-HING/FILEBOX/raw/master/1565402458929.jpg)
